#!/bin/sh
set -e

HERMES_HOME="${HERMES_HOME:-/data/hermes}"

mkdir -p "$HERMES_HOME/sessions" \
         "$HERMES_HOME/logs" \
         "$HERMES_HOME/memories" \
         "$HERMES_HOME/cron" \
         "$HERMES_HOME/skills" \
         "$HERMES_HOME/workspace"

# Bootstrap .env (first run only)
if [ ! -f "$HERMES_HOME/.env" ]; then
    echo "# Auto-generated by docker-entrypoint.sh on first run" > "$HERMES_HOME/.env"

    for var in \
        OPENROUTER_API_KEY \
        LLM_MODEL \
        GLM_API_KEY \
        GLM_BASE_URL \
        KIMI_API_KEY \
        KIMI_BASE_URL \
        MINIMAX_API_KEY \
        MINIMAX_BASE_URL \
        MINIMAX_CN_API_KEY \
        MINIMAX_CN_BASE_URL \
        TELEGRAM_BOT_TOKEN \
        TELEGRAM_ALLOWED_USERS \
        DISCORD_BOT_TOKEN \
        DISCORD_ALLOWED_USERS \
        SLACK_BOT_TOKEN \
        SLACK_APP_TOKEN \
        SLACK_ALLOWED_USERS \
        WHATSAPP_ENABLED \
        WHATSAPP_ALLOWED_USERS \
        GATEWAY_ALLOW_ALL_USERS \
        FIRECRAWL_API_KEY \
        FAL_KEY \
        HONCHO_API_KEY \
        VOICE_TOOLS_OPENAI_KEY \
        BROWSERBASE_API_KEY \
        BROWSERBASE_PROJECT_ID \
        BROWSERBASE_PROXIES \
        BROWSERBASE_ADVANCED_STEALTH \
        BROWSER_SESSION_TIMEOUT \
        BROWSER_INACTIVITY_TIMEOUT \
        TINKER_API_KEY \
        WANDB_API_KEY \
        RL_API_URL \
        GITHUB_TOKEN \
        HERMES_HUMAN_DELAY_MODE \
        HERMES_HUMAN_DELAY_MIN_MS \
        HERMES_HUMAN_DELAY_MAX_MS \
        WEB_TOOLS_DEBUG \
        VISION_TOOLS_DEBUG \
        MOA_TOOLS_DEBUG \
        IMAGE_TOOLS_DEBUG \
        TERMINAL_TIMEOUT \
        TERMINAL_LIFETIME_SECONDS \
    ; do
        eval "val=\${$var:-}"
        if [ -n "$val" ]; then
            echo "${var}=${val}" >> "$HERMES_HOME/.env"
        fi
    done

    echo "Bootstrap: wrote $HERMES_HOME/.env"
fi

# Bootstrap config.yaml (first run only)
if [ ! -f "$HERMES_HOME/config.yaml" ]; then
    cat > "$HERMES_HOME/config.yaml" <<'YAML'
model:
  default: "anthropic/claude-opus-4.6"
  provider: "auto"

terminal:
  backend: "local"
  cwd: "/data/hermes/workspace"
  timeout: 180
  lifetime_seconds: 300

compression:
  enabled: true
  threshold: 0.85
  summary_model: "google/gemini-3-flash-preview"

memory:
  memory_enabled: true
  user_profile_enabled: true

session_reset:
  mode: both
  idle_minutes: 1440
  at_hour: 4

toolsets:
  - all
YAML

    echo "Bootstrap: wrote $HERMES_HOME/config.yaml"
fi

case "$1" in
    gateway)
        exec hermes gateway
        ;;
    cli)
        shift
        exec hermes chat "$@"
        ;;
    *)
        exec "$@"
        ;;
esac
